
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class C_ProcesoParaEjecucion
{

    public Nullable<int> Id_AprobacionProgramacionPeriodica { get; set; }

    public Nullable<int> Id_SolicitudEjecucionPorDemanda { get; set; }

    public string Nombre_Proceso { get; set; }

    public Nullable<System.TimeSpan> Hora_EjecucionProgramada { get; set; }

    public string Nombre_AreaNegocio { get; set; }

    public string Nombre_CarpetaWorkflows { get; set; }

    public int Id_Proceso { get; set; }

    public Nullable<int> Id_ProgramacionPeriodica { get; set; }

    public string Cb_RevisionAutomaticaUsuario { get; set; }

    public string Cb_RevisionAutomaticaOperador { get; set; }

}

}
