
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class C_ProcesoProgramado
{

    public System.DateTime Fecha { get; set; }

    public int Id_ProgramacionPeriodica { get; set; }

    public int Id_AprobacionProgramacionPeriodica { get; set; }

    public int Id_SolicitudEjecucionPorDemanda { get; set; }

    public int Id_Proceso { get; set; }

    public string Nombre_Proceso { get; set; }

    public Nullable<System.TimeSpan> Hora_EjecucionProgramada { get; set; }

    public int Id_AreaNegocio { get; set; }

    public string Nombre_AreaNegocio { get; set; }

    public string Nombre_CarpetaWorkflows { get; set; }

    public string Cb_Vencido { get; set; }

    public string Cb_ProgramacionAprobada { get; set; }

    public string Cb_ProcesoEjecutado { get; set; }

    public Nullable<System.DateTime> FechaHora_InicioEjecucion { get; set; }

    public Nullable<System.DateTime> FechaHora_FinEjecucion { get; set; }

    public Nullable<int> Id_EstadoEjecucionInformatica { get; set; }

    public string Nombre_EstadoEjecucionInformatica { get; set; }

    public Nullable<int> Id_EstadoOperadorEjecucionProceso { get; set; }

    public string Nombre_EstadoOperadorEjecucionProceso { get; set; }

    public Nullable<int> Id_EstadoUsuarioEjecucionProceso { get; set; }

    public string Nombre_EstadoUsuarioEjecucionProceso { get; set; }

    public Nullable<int> Id_ResultadoEjecucionProgramada { get; set; }

    public string Cb_RevisionAutomaticaUsuario { get; set; }

    public string Cb_RevisionAutomaticaOperador { get; set; }

    public string Cb_Activo { get; set; }

}

}
