

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BI_OPERACIONEntities : DbContext
{
    public BI_OPERACIONEntities()
        : base("name=BI_OPERACIONEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<OPE_AprobacionProgramacionPeriodicaProceso> OPE_AprobacionProgramacionPeriodicaProceso { get; set; }

    public virtual DbSet<OPE_AreaNegocio> OPE_AreaNegocio { get; set; }

    public virtual DbSet<OPE_EstadoEjecucionProceso> OPE_EstadoEjecucionProceso { get; set; }

    public virtual DbSet<OPE_HorarioSistemaFuente> OPE_HorarioSistemaFuente { get; set; }

    public virtual DbSet<OPE_Proceso> OPE_Proceso { get; set; }

    public virtual DbSet<OPE_ProcesoPrerequisito> OPE_ProcesoPrerequisito { get; set; }

    public virtual DbSet<OPE_ProgramacionPeriodicaProceso> OPE_ProgramacionPeriodicaProceso { get; set; }

    public virtual DbSet<OPE_Rel_Proceso_ProcesoGestor> OPE_Rel_Proceso_ProcesoGestor { get; set; }

    public virtual DbSet<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada { get; set; }

    public virtual DbSet<OPE_RutaPrerequisitoProceso> OPE_RutaPrerequisitoProceso { get; set; }

    public virtual DbSet<OPE_SistemaFuente> OPE_SistemaFuente { get; set; }

    public virtual DbSet<OPE_SolicitudEjecucionPorDemandaProceso> OPE_SolicitudEjecucionPorDemandaProceso { get; set; }

    public virtual DbSet<OPE_TipoSistemaFuente> OPE_TipoSistemaFuente { get; set; }

    public virtual DbSet<OPE_PeriodicidadProceso> OPE_PeriodicidadProceso { get; set; }

    public virtual DbSet<OPE_DiaSemana> OPE_DiaSemana { get; set; }

    public virtual DbSet<OPE_Fecha> OPE_Fecha { get; set; }

    public virtual DbSet<C_ProcesoParaEjecucion> C_ProcesoParaEjecucion { get; set; }

    public virtual DbSet<C_ProcesoProgramado> C_ProcesoProgramado { get; set; }

    public virtual DbSet<OPE_AuditoriaUsuario> OPE_AuditoriaUsuario { get; set; }

    public virtual DbSet<OPE_Parametro> OPE_Parametro { get; set; }

    public virtual DbSet<OPE_PerfilUsuario> OPE_PerfilUsuario { get; set; }

    public virtual DbSet<OPE_TipoActividadUsuario> OPE_TipoActividadUsuario { get; set; }

    public virtual DbSet<OPE_TipoEjecucionDemanda> OPE_TipoEjecucionDemanda { get; set; }

    public virtual DbSet<OPE_Usuario> OPE_Usuario { get; set; }

}

}

