

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TDEntities : DbContext
{
    public TDEntities()
        : base("name=TDEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<TP_Parametros_BI> TP_Parametros_BI { get; set; }

}

}

