
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_ProgramacionPeriodicaProcesoHFSM
{

    public int Id_ProgramacionPeriodica { get; set; }

    public int Id_Periodicidad { get; set; }

    public Nullable<short> Num_DiaMes { get; set; }

    public Nullable<short> Num_MesPeriodo { get; set; }

    public Nullable<short> Num_Semana { get; set; }

    public Nullable<System.TimeSpan> Hora_Ejecucion { get; set; }

    public int Id_Proceso { get; set; }

    public Nullable<System.DateTime> Fecha_Eliminado { get; set; }

    public System.DateTime Fecha_Creacion { get; set; }

}

}
