
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_HorarioSistemaFuente
{

    public System.TimeSpan Hora_Inicio { get; set; }

    public System.TimeSpan Hora_Fin { get; set; }

    public int Id_SistemaFuente { get; set; }



    protected virtual OPE_SistemaFuente OPE_SistemaFuente { get; set; }

}

}
