
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_RutaPrerequisitoProceso
{

    public string Desc_RutaArchivo { get; set; }

    public int Id_Proceso { get; set; }

    public int Id_RutaPrerequisito { get; set; }



    protected virtual OPE_Proceso OPE_Proceso { get; set; }

}

}
