
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_Usuario
{

    public int Id_Usuario { get; set; }

    public string Nombre_Usuario { get; set; }

    public Nullable<int> Id_PerfilUsuario { get; set; }

    public Nullable<int> Id_AreaNegocio { get; set; }

    public string Desc_JSONMenuUsuario { get; set; }



    public virtual OPE_PerfilUsuario OPE_PerfilUsuario { get; set; }

}

}
