
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_AuditoriaUsuario
{

    public Nullable<System.DateTime> FechaHora_Actividad { get; set; }

    public int Id_TipoActividadUsuario { get; set; }

    public string Desc_Actividad { get; set; }

    public int Id_AuditoriaUsuario { get; set; }

    public string Nombre_Usuario { get; set; }

    public string Desc_DetalleActividad { get; set; }



    public virtual OPE_TipoActividadUsuario OPE_TipoActividadUsuario { get; set; }

}

}
