
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_Parametro
{

    public int Id_Parametro { get; set; }

    public string Nombre_Parametro { get; set; }

    public string Valor_Parametro { get; set; }

    public string Desc_Parametro { get; set; }

    public string Nombre_GrupoParametro { get; set; }

}

}
