
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_SolicitudEjecucionPorDemandaProceso
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_SolicitudEjecucionPorDemandaProceso()
    {

        this.OPE_ResultadoEjecucionProgramada = new HashSet<OPE_ResultadoEjecucionProgramada>();

    }


    public int Id_SolicitudEjecucionPorDemanda { get; set; }

    public Nullable<System.DateTime> FechaHora_FinVentanaSugerida { get; set; }

    public Nullable<System.DateTime> FechaHora_EjecucionAprobada { get; set; }

    public int Id_Proceso { get; set; }

    public Nullable<System.DateTime> FechaHora_InicioVentanaSugerida { get; set; }

    public Nullable<System.DateTime> FechaHora_Sugerida { get; set; }

    public Nullable<System.DateTime> FechaHora_RevisionUsuario { get; set; }

    public Nullable<System.DateTime> FechaHora_RevisionOperador { get; set; }

    public string Nombre_OperadorRevisor { get; set; }

    public string Nombre_RolOperadorRevisor { get; set; }

    public string Nombre_UsuarioSolicitante { get; set; }

    public string Nombre_RolUsuarioSolicitante { get; set; }

    public string Cb_Activo { get; set; }

    public string Desc_JustificacionSolicitud { get; set; }

    public Nullable<int> Id_TipoEjecucionDemanda { get; set; }



    protected virtual OPE_Proceso OPE_Proceso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada { get; set; }

}

}
