
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_PeriodicidadProceso
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_PeriodicidadProceso()
    {

        this.OPE_ProgramacionPeriodicaProceso = new HashSet<OPE_ProgramacionPeriodicaProceso>();

    }


    public int Id_Periodicidad { get; set; }

    public string Nombre_Periodicidad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    protected virtual ICollection<OPE_ProgramacionPeriodicaProceso> OPE_ProgramacionPeriodicaProceso { get; set; }

}

}
