
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_AreaNegocio
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_AreaNegocio()
    {

        this.OPE_Proceso = new HashSet<OPE_Proceso>();

    }


    public int Id_AreaNegocio { get; set; }

    public string Desc_AreaNegocio { get; set; }

    public string Nombre_AreaNegocio { get; set; }

    public string Nombre_CarpetaWorkflows { get; set; }

    public Nullable<int> Num_InicioRangoCodProceso { get; set; }

    public Nullable<int> Num_FinRangoCodProceso { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    protected virtual ICollection<OPE_Proceso> OPE_Proceso { get; set; }

}

}
