
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_SistemaFuente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_SistemaFuente()
    {

        this.OPE_HorarioSistemaFuente = new HashSet<OPE_HorarioSistemaFuente>();

        this.OPE_Proceso = new HashSet<OPE_Proceso>();

    }


    public int Id_SistemaFuente { get; set; }

    public string Nombre_SistemaFuente { get; set; }

    public int Id_TipoSistemaFuente { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_HorarioSistemaFuente> OPE_HorarioSistemaFuente { get; set; }

    public virtual OPE_TipoSistemaFuente OPE_TipoSistemaFuente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    protected virtual ICollection<OPE_Proceso> OPE_Proceso { get; set; }

}

}
