
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_TipoSistemaFuente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_TipoSistemaFuente()
    {

        this.OPE_SistemaFuente = new HashSet<OPE_SistemaFuente>();

    }


    public int Id_TipoSistemaFuente { get; set; }

    public string Nombre_TipoSistemaFuente { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    protected virtual ICollection<OPE_SistemaFuente> OPE_SistemaFuente { get; set; }

}

}
