
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_Fecha
{

    public System.DateTime Fecha { get; set; }

    public int Num_DiaMes { get; set; }

    public int Num_MesBimestre { get; set; }

    public int Num_MesTrimestre { get; set; }

    public int Num_MesSemestre { get; set; }

    public int Num_Anio { get; set; }

    public int Num_Semestre { get; set; }

    public int Num_Trimestre { get; set; }

    public int Num_Bimestre { get; set; }

    public int Num_Mes { get; set; }

    public int Num_SemanaAnio { get; set; }

    public int Num_SemanaMes { get; set; }

    public int Num_DiaSemana { get; set; }

    public int Num_DiaAnio { get; set; }

    public string Cb_EsFestivoNacional { get; set; }

    public string Desc_FestivoNacional { get; set; }

    public string Cb_EsNoHabilCUD { get; set; }

    public System.DateTime Fecha_UltimoDiaMes { get; set; }

}

}
