
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_EstadoEjecucionProceso
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_EstadoEjecucionProceso()
    {

        this.OPE_ResultadoEjecucionProgramada = new HashSet<OPE_ResultadoEjecucionProgramada>();

        this.OPE_ResultadoEjecucionProgramada1 = new HashSet<OPE_ResultadoEjecucionProgramada>();

        this.OPE_ResultadoEjecucionProgramada2 = new HashSet<OPE_ResultadoEjecucionProgramada>();

    }


    public int Id_EstadoEjecucion { get; set; }

    public string Nombre_EstadoEjecucion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada2 { get; set; }

}

}
