
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_ResultadoEjecucionProgramada
{

    public Nullable<System.DateTime> FechaHora_InicioEjecucion { get; set; }

    public Nullable<System.DateTime> FechaHora_FinEjecucion { get; set; }

    public int Id_ResultadoEjecucionProgramada { get; set; }

    public Nullable<int> Id_SolicitudEjecucionPorDemanda { get; set; }

    public Nullable<int> Id_AprobacionProgramacionPeriodica { get; set; }

    public Nullable<System.DateTime> FechaHora_RevisionOperador { get; set; }

    public Nullable<System.DateTime> FechaHora_RevisionUsuario { get; set; }

    public Nullable<int> Id_EstadoOperadorEjecucionProceso { get; set; }

    public Nullable<int> Id_EstadoUsuarioEjecucionProceso { get; set; }

    public int Id_EstadoEjecucionInformatica { get; set; }

    public string Nombre_UsuarioRevisor { get; set; }

    public string Nombre_OperadorRevisor { get; set; }

    public string Nombre_RolUsuarioRevisor { get; set; }

    public string Nombre_RolOperadorRevisor { get; set; }

    public int Id_Proceso { get; set; }

    public Nullable<int> Id_ProgramacionPeriodica { get; set; }



    protected virtual OPE_AprobacionProgramacionPeriodicaProceso OPE_AprobacionProgramacionPeriodicaProceso { get; set; }

    protected virtual OPE_EstadoEjecucionProceso OPE_EstadoEjecucionProceso { get; set; }

    protected virtual OPE_EstadoEjecucionProceso OPE_EstadoEjecucionProceso1 { get; set; }

    protected virtual OPE_EstadoEjecucionProceso OPE_EstadoEjecucionProceso2 { get; set; }

    protected virtual OPE_SolicitudEjecucionPorDemandaProceso OPE_SolicitudEjecucionPorDemandaProceso { get; set; }

    public virtual OPE_Proceso OPE_Proceso { get; set; }

}

}
