
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_TipoActividadUsuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_TipoActividadUsuario()
    {

        this.OPE_AuditoriaUsuario = new HashSet<OPE_AuditoriaUsuario>();

    }


    public int Id_TipoActividadUsuario { get; set; }

    public string Nombre_TipoActividadUsuario { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_AuditoriaUsuario> OPE_AuditoriaUsuario { get; set; }

}

}
