
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OPE_AprobacionProgramacionPeriodicaProceso
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPE_AprobacionProgramacionPeriodicaProceso()
    {

        this.OPE_ResultadoEjecucionProgramada = new HashSet<OPE_ResultadoEjecucionProgramada>();

    }


    public int Id_ProgramacionPeriodica { get; set; }

    public Nullable<System.DateTime> FechaHora_RevisionOperador { get; set; }

    public int Id_AprobacionProgramacionPeriodica { get; set; }

    public string Nombre_OperadorRevisor { get; set; }

    public string Nombre_RolOperadorRevisor { get; set; }

    public Nullable<System.DateTime> Fecha_EjecucionAprobada { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPE_ResultadoEjecucionProgramada> OPE_ResultadoEjecucionProgramada { get; set; }

    public virtual OPE_ProgramacionPeriodicaProceso OPE_ProgramacionPeriodicaProceso { get; set; }

}

}
