
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TP_Parametros_BI
{

    public int Id_Parametro { get; set; }

    public string NombreGrupoParametro { get; set; }

    public string NombreParametro { get; set; }

    public string ValorParametro { get; set; }

    public string DescripcionParametro { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

}

}
